### ISSUE TITLE
Permaliks to apps

### ISSUE THREAD

**Issue by derhagen** [jkelol111/webstore#6]
**Is your feature request related to a problem? Please describe.**
When I find an interesting app on the store, I might like to show it to a friend by sending a link.

**Describe the solution you'd like**
Being able to copy an app-specific permalink like `https://jkelol111.github.io/webstore/covid-19-numbers` that shows the modal including screenshots, description, download button when opened.

Additional: If the app has a category, it might make sense to open this category in the background to allow closing the modal and finding the app again.

**Comment by jkelol111** [comment]
Hello, sorry for the late reply, I have been quite busy with life lately. I may try to implement these by giving the cards some ids that could be copied to the clipboard via a button on the card.

**Comment by jkelol111** [comment]
The issue is fixed. You can make a link that refers to your app's slug, and the page will be navigated accordingly, such as: 

jkelol111.github.io/webstore/#telegram

**Comment by jkelol111** [comment]
Nevermind, I will reopen this, looks like there are still some rough edges to work around.

**Comment by jkelol111** [comment]
Hi, there should be an option for linking to the app card now.

**Comment by jm42** [comment]
This still not working for me. Opening https://store.bananahackers.net/#plastic-map will show the toast of data loaded, then the toast of apps loaded, but won't open the app card.

**Comment by jkelol111** [comment]
I'm aware of this problem. Will poke around when I have time.

**Comment by jkelol111** [comment]
Should be fixed now.
